### ISSUE TITLE
remove corner radius from cells

### ISSUE THREAD

**Issue by sgandro** [gtsif21/UITags#5]
Hi,
greet job! Please! Can you add cell corner radius to params ?

Thanks a lot

**Comment by gtsifrikas** [comment]
Hi, 
I’m preparing an update with lots of improvements, i’ll add that also!
 Thank you!

**Comment by sgandro** [comment]
I need to insert UITags inside tableViewCell and change tableViewCell height dynamically so collectionView not scrolled :-)

**Comment by gtsifrikas** [comment]
the problem is that UITags essentially is a UICollectionView, and that view takes time to init so i think i should calculate "by hand" the intrinsicContentSize so when the UICollectionView loads the space that would need would be there already

**Comment by gtsifrikas** [comment]
A temp solution to your problem if your table view do not have a lot of rows, init at the beginning of your view controller lifecycle all the UITags views you would need, implement the heightForRow method and return the UITags.collectionView.contentSize.height for each row.
